<?php 
    $title = "Application Submitted | PharMediSync";
    include APPPATH . 'Views/shared/pg_header.php'; 
?>

<div class="glass-card text-center" style="max-width: 500px; padding: 60px 40px;">
    <!-- Confetti Emoji/Icon -->
    <div class="mb-4">
        <span style="font-size: 60px;">🎉</span>
    </div>

    <h2 class="fw-bold mb-3" style="font-size: 28px; letter-spacing: -0.5px;">Application Submitted!</h2>
    
    <div class="px-3">
        <p class="text-white-50 mb-4" style="font-size: 12px; line-height: 1.6;">
            Your institutional client account application has been received by <br>
            <b class="text-white">Robin Rose Trading</b>.
        </p>

        <p class="text-white-50 mb-5" style="font-size: 11px;">
            You will receive a confirmation email within <b class="text-white">24-48 hours</b> <br>
            once your account is reviewed and approved.
        </p>
    </div>

    <!-- Application Reference (Generated by Controller) -->
    <div class="p-2 px-4 rounded-pill d-inline-block mb-5" style="background: rgba(52, 152, 219, 0.15); border: 1px solid rgba(52, 152, 219, 0.3);">
        <small class="text-white fw-bold" style="font-size: 10px; letter-spacing: 0.5px;">
            ✓ Application Reference: <?= esc($reference) ?>
        </small>
    </div>

    <div class="mt-2">
        <a href="<?= base_url('partner-gateway') ?>" class="btn-pg-primary w-100 py-3 shadow-lg text-decoration-none">
            Now Login
        </a>
    </div>
</div>

<?php include APPPATH . 'Views/shared/pg_footer.php'; ?>